In [1]:
import base64
import json
import logging
import os
import time
import requests
import pandas as pd

logger = logging.getLogger(__name__)
logger.setLevel(logging.DEBUG)
dh = logging.FileHandler("debug.log", encoding="utf-8")
dh.setLevel(logging.DEBUG)
eh = logging.FileHandler("error.log", encoding="utf-8")
eh.setLevel(logging.ERROR)
formatter = logging.Formatter("%(asctime)s-%(name)s-%(levelname)s-%(message)s")
dh.setFormatter(formatter)
eh.setFormatter(formatter)
logger.addHandler(eh)
logger.addHandler(dh)

H = {"User-Agent": "hse-bbi-237-student", "Accept": "application/vnd.github+json"}
# https://yandex.ru/search/?text=как+добавить+токен+в+google+colab&clid=1955453&win=723&lr=213
# https://colab.research.google.com/github/google-gemini/cookbook/blob/main/quickstarts/Authentication_with_OAuth.ipynb
try:
    from google.colab import userdata
    os.environ["GITHUB_TOKEN"] = userdata.get("GITHUB_TOKEN")
except ImportError:
    pass
tk = os.environ.get("GITHUB_TOKEN")
if tk:
    H["Authorization"] = f"Bearer {tk}"


def get_json(url, params=None):
    n_stop = 0
    while True:
        logger.debug(f"GET_JSON {url} params={params}")
        r = requests.get(url, params=params, headers=H)
        # Ошибки подбирались потом и кровью. Обе ошибки встречали при скачке
        if r.status_code in (403, 429):
            logger.warning(f"GET_JSON rate_limit {url} {r.status_code} {r!r}")
            n_stop += 1
            if n_stop >= 2:
                return r
            time.sleep(60)
            continue
        # time.sleep(0.5)
        return r

In [ ]:
# seen = set()
# users = []
# req_n = 0
# p = 1
# while p <= 10:
#     logger.debug(f"SEARCH_USERS page={p}")
#     r = get_json(
#         "https://api.github.com/search/users",
#         params={"q": "location:Russia", "per_page": 100, "page": p},
#     )
#     try:
#         b = r.json()["items"]
#     except (ValueError, KeyError, TypeError):
#         break
#     if not b:
#         break
#     for u in b:
#         try:
#             uid = u["id"]
#             lg = u["login"]
#             if uid in seen:
#                 continue
#             seen.add(uid)
#             ru = get_json(f"https://api.github.com/users/{lg}")
#             req_n += 1
#             if ru.status_code == 200:
#                 users.append(ru.json())
#             else:
#                 users.append(u)
#             with open("users.json", "w", encoding="utf-8") as f:
#                 json.dump(users, f, ensure_ascii=False, indent=2)
#             if req_n % 100 == 0:
#                 logger.debug(f"USERS_PROGRESS {req_n} {len(users)}")
#         except (KeyError, TypeError, ValueError):
#             continue
#     if len(b) < 100:
#         break
#     p += 1

# df_users = pd.json_normalize(users, sep="_")
# df_users

DEBUG:__main__:SEARCH_USERS page=1
DEBUG:__main__:GET_JSON https://api.github.com/search/users params={'q': 'location:Russia', 'per_page': 100, 'page': 1}
DEBUG:__main__:GET_JSON https://api.github.com/users/Kwynto params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/K1rsN7 params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/DIMFLIX params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/ValdikSS params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/nfterrax params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/carlcastanas params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/cepseu1 params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/yandex params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/alexey-goloburdin params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/codersgyan params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/yandexdataschool params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/KEV0143 params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/dstogov params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/Good4lien params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/sergeche params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/esokolov params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/Dmitriy-Vas params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/StanislavPetrovV params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/Bo0oM params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/grishka params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/mybatis params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/kmike params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/Dyakonov params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/alexander-akait params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/antonkomarev params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/swabird params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/T8RIN params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/Prototik params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/enghamzasalem params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/nsf params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/klen params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/extremecodetv params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/VKCOM params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/tigertv params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/number571 params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/barancev params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/nshmyrev params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/istarkov params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/DosX-dev params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/tilir params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/lorien params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/dkurt params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/artdeell params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/FilimonovAlexey params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/vpisarev params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/4n70w4 params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/bravekirty params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/milabs params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/AlexGladkov params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/anticensority params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/harryheman params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/tg-bomze params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/developer01234 params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/Quarx2k params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/floatdrop params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/alalek params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/mrDIMAS params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/lisyarus params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/bb33bb params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/aleksanderlamkov params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/shwanoff params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/MzHmO params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/VladimirBalun params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/ellen-simonyan params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/TheAndreyZakharov params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/KANKOSHEV params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/Irina-Smol params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/veged params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/enhorse params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/Kerminator1973 params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/nikita-volkov params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/kolyvan params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/shivaya-dav params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/ozkriff params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/Domaman202 params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/poma params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/HopelessCompass params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/timscriptov params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/maxlapshin params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/peterarsentev params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/Friend-LGA params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/alexander-ladygin params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/catamphetamine params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/mrmlnc params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/Blueberryy params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/ldpreload params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/monosans params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/vlasovskikh params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/VladislavEremeev params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/Nashatyrev params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/TotallyNotAHaxxer params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/maxzaikin params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/SoberGrim params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/cepseu6 params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/ilyhalight params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/TheNewAttacker64 params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/darkk params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/DmitryTsepelev params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/jkenix params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/PawelStepanov params=None
DEBUG:__main__:USERS_PROGRESS 100 100
DEBUG:__main__:SEARCH_USERS page=2
DEBUG:__main__:GET_JSON https://api.github.com/search/users params={'q': 'location:Russia', 'per_page': 100, 'page': 2}
DEBUG:__main__:GET_JSON https://api.github.com/users/tigr1234566 params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/Skeltex params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/nukeykt params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/grafov params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/seregazhuk params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/pauljamm params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/aemeltsev params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/CODeRUS params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/ddemidov params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/webmakaka params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/funny-falcon params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/ac3ss0r params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/kushti params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/EvilBeaver params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/pConst params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/NekR params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/I-Atlas params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/artpolikarpov params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/crashmax-dev params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/vk-com params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/ufocoder params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/Pyscodes-pro params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/JustS-js params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/tabuna params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/RAUH-WRLD params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/true-grue params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/neon-age params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/khusnetdinov params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/radioegor146 params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/arepina params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/z3APA3A params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/miripiruni params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/denisshevchenko params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/Chaosus params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/bezumkin params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/aleksandrresetnikov params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/JetBrain2056 params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/M0rtyMerr params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/petrochenkov params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/tsergeytovarov params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/yeriomin params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/natasha params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/akopytov params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/Calabonga params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/andrey-helldar params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/ivmai params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/Wohlstand params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/le0nklcpp params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/leffff params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/s1lentq params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/Koziev params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/arduanov params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/sergiomarotco params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/kovaldn params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/scratcher28 params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/Naltox params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/disintegration params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/FlatL1neAPT params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/IlyasYOY params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/mediaexplorer74 params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/foxcpp params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/BOOtak params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/cattyngmd params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/cy6erGn0m params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/unlight params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/sozykin params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/annblok params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/n4kz params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/Piterden params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/chebupelka8 params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/RinatValiullov params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/theVakhovskeIsTaken params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/anton-k params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/kuviman params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/mancj params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/dreamerenigma params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/artemiosdev params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/maruki00 params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/SnowVolf params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/Kxrma47 params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/ermakovich params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/Beeblerox params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/3F params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/glebmachine params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/urkazan16 params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/VBart params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/brainopia params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/subzey params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/StressOzz params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/Mithgol params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/worldbeater params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/buriy params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/Ahora57 params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/stascorp params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/fomkin params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/MaximSmolskiy params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/red-prig params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/Daniil-Osokin params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/ziggi params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/melnik909 params=None
DEBUG:__main__:USERS_PROGRESS 200 200
DEBUG:__main__:SEARCH_USERS page=3
DEBUG:__main__:GET_JSON https://api.github.com/search/users params={'q': 'location:Russia', 'per_page': 100, 'page': 3}
DEBUG:__main__:GET_JSON https://api.github.com/users/AGaevskiy params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/reo7sp params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/vtolstov params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/lRomul params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/Pr-Mex params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/frenzzy params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/bakNa2t params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/r57zone params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/mikessh params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/archimag params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/agricolamz params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/laboshinl params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/edotoday params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/durov params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/vladimir-bukhtoyarov params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/constverum params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/js-neo params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/AlexanderPro params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/MisterZtr params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/Elytrium params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/wajahat-ali-mir-dev params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/pumPCin params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/Fayzimurod params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/TikhomirovSergey params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/gkv311 params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/koroteevmv params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/mihdan params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/0xPh0enix params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/zelenin params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/yeputons params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/EMIR1HUB params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/GnuriaN params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/zevlg params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/mr-dvlpr params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/a-legotin params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/TDenisM params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/ded32 params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/MeeXaSiK params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/dshemin params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/dv0retsky params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/IvanArkhipov1999 params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/PolarNick239 params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/idlesign params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/a1exdandy params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/Pan4ur params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/InoriRus params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/Vagif85 params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/user params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/varlesh params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/MoonFox2006 params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/Eiden-one params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/lazychaser params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/maloy85 params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/HackerDev-Felix params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/Murcha1990 params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/0niel params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/maxbarsukov params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/ingarbi params=None
DEBUG:__main__:GET_JSON https://api.github.com/users/alex-w params=None

,login,id,node_id,avatar_url,gravatar_id,url,html_url,followers_url,following_url,gists_url,...,email,hireable,bio,twitter_username,public_repos,public_gists,followers,following,created_at,updated_at
0,Kwynto,31433211,MDQ6VXNlcjMxNDMzMjEx,https://avatars.githubusercontent.com/u/314332...,,https://api.github.com/users/Kwynto,https://github.com/Kwynto,https://api.github.com/users/Kwynto/followers,https://api.github.com/users/Kwynto/following{...,https://api.github.com/users/Kwynto/gists{/gis...,...,None,None,"Programmers have existed in all ages, and were...",None,20,2,14247,7,2017-08-29T07:10:05Z,2026-03-01T17:53:12Z
1,K1rsN7,123446875,U_kgDOB1umWw,https://avatars.githubusercontent.com/u/123446...,,https://api.github.com/users/K1rsN7,https://github.com/K1rsN7,https://api.github.com/users/K1rsN7/followers,https://api.github.com/users/K1rsN7/following{...,https://api.github.com/users/K1rsN7/gists{/gis...,...,None,None,‍💻 Data Scientist | 👨‍🎓 Student |\r\nI use @me...,None,22,2,9303,9898,2023-01-24T07:44:21Z,2026-04-05T16:27:28Z
2,DIMFLIX,112165977,U_kgDOBq-EWQ,https://avatars.githubusercontent.com/u/112165...,,https://api.github.com/users/DIMFLIX,https://github.com/DIMFLIX,https://api.github.com/users/DIMFLIX/followers,https://api.github.com/users/DIMFLIX/following...,https://api.github.com/users/DIMFLIX/gists{/gi...,...,None,None,I use @meowrch btw,None,19,0,9109,9615,2022-08-26T09:16:48Z,2026-03-17T11:34:57Z
3,ValdikSS,3054729,MDQ6VXNlcjMwNTQ3Mjk=,https://avatars.githubusercontent.com/u/305472...,,https://api.github.com/users/ValdikSS,https://github.com/ValdikSS,https://api.github.com/users/ValdikSS/followers,https://api.github.com/users/ValdikSS/followin...,https://api.github.com/users/ValdikSS/gists{/g...,...,iam@valdikss.org.ru,None,None,None,69,24,5167,0,2012-12-16T09:09:59Z,2026-03-07T22:56:11Z
4,nfterrax,97410466,U_kgDOBc5dog,https://avatars.githubusercontent.com/u/974104...,,https://api.github.com/users/nfterrax,https://github.com/nfterrax,https://api.github.com/users/nfterrax/followers,https://api.github.com/users/nfterrax/followin...,https://api.github.com/users/nfterrax/gists{/g...,...,hello@nfterrax.online,None,Crypto-Enthusiast | Web3 Community Manager | W...,nfterrax,4,0,3484,6,2022-01-09T20:57:08Z,2026-03-09T11:51:10Z
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,Reavolt,41386274,MDQ6VXNlcjQxMzg2Mjc0,https://avatars.githubusercontent.com/u/413862...,,https://api.github.com/users/Reavolt,https://github.com/Reavolt,https://api.github.com/users/Reavolt/followers,https://api.github.com/users/Reavolt/following...,https://api.github.com/users/Reavolt/gists{/gi...,...,reavolt@outlook.com,True,Everyone underwent something that changed him,None,9,0,49,19,2018-07-18T16:32:47Z,2026-03-28T12:21:43Z
996,zapletnev,1358172,MDQ6VXNlcjEzNTgxNzI=,https://avatars.githubusercontent.com/u/135817...,,https://api.github.com/users/zapletnev,https://github.com/zapletnev,https://api.github.com/users/zapletnev/followers,https://api.github.com/users/zapletnev/followi...,https://api.github.com/users/zapletnev/gists{/...,...,igor.zapletnev@gmail.com,None,None,None,9,1,49,22,2012-01-20T13:39:25Z,2026-03-26T04:25:01Z
997,DoctorWebLtd,3381928,MDEyOk9yZ2FuaXphdGlvbjMzODE5Mjg=,https://avatars.githubusercontent.com/u/338192...,,https://api.github.com/users/DoctorWebLtd,https://github.com/DoctorWebLtd,https://api.github.com/users/DoctorWebLtd/foll...,https://api.github.com/users/DoctorWebLtd/foll...,https://api.github.com/users/DoctorWebLtd/gist...,...,pr@drweb.com,None,None,None,9,0,49,0,2013-01-25T13:57:36Z,2016-02-27T06:00:08Z
998,meetanthony,10683674,MDQ6VXNlcjEwNjgzNjc0,https://avatars.githubusercontent.com/u/106836...,,https://api.github.com/users/meetanthony,https://github.com/meetanthony,https://api.github.com/users/meetanthony/follo...,https://api.github.com/users/meetanthony/follo...,https://api.github.com/users/meetanthony/gists...,...,None,None,None,None,17,0,49,20,2015-01-24T12:01:46Z,2026-04-05T08:44:17Z
999,labdmitriy,9625027,MDQ6VXNlcjk2MjUwMjc=,https://avatars.githubusercontent.com/u/962502...,,https://api.github.com/users/labdmitriy,https://github.com/labdmitriy,https://api.github.com/users/labdmitriy/followers,https://api.github.com/users/labdmitriy/follow...,https://api.github.com/users/labdmitriy/gists{...,...,labdmitriy@gmail.com,True,None,None,43,0,49,64,2014-11-08T12:17:25Z,2026-03-26T18:23:36Z

In [2]:
with open("users.json", encoding="utf-8") as f:
    users = json.load(f)
df_users = pd.json_normalize(users, sep="_")

In [ ]:
# rows = []
# open("repos.jsonl", "w", encoding="utf-8").close()
# req_n = 0
# for k in df_users.index:
#     lg = df_users.at[k, "login"]
#     pr = df_users.at[k, "public_repos"]
#     # if pd.notna(pr) and pr >= 30:
#     #     continue
#     p = 1
#     while True:
#         rr = get_json(
#             f"https://api.github.com/users/{lg}/repos",
#             params={"per_page": 100, "page": p},
#         )
#         req_n += 1
#         if req_n % 100 == 0:
#             logger.debug(f"REPOS_REQ {req_n}")
#         if rr.status_code != 200:
#             break
#         try:
#             b = rr.json()
#         except ValueError:
#             break
#         if not b:
#             break
#         for x in b:
#             x["sample_user_login"] = lg
#             rows.append(x)
#             with open("repos.jsonl", "a", encoding="utf-8") as f:
#                 f.write(json.dumps(x, ensure_ascii=False) + "\n")
#         if len(b) < 100:
#             break
#         p += 1

# df_repos = pd.json_normalize(rows, sep="_")
# df_repos

DEBUG:__main__:GET_JSON https://api.github.com/users/Kwynto/repos params={'per_page': 100, 'page': 1}
DEBUG:__main__:GET_JSON https://api.github.com/users/K1rsN7/repos params={'per_page': 100, 'page': 1}
DEBUG:__main__:GET_JSON https://api.github.com/users/DIMFLIX/repos params={'per_page': 100, 'page': 1}
DEBUG:__main__:GET_JSON https://api.github.com/users/ValdikSS/repos params={'per_page': 100, 'page': 1}
DEBUG:__main__:GET_JSON https://api.github.com/users/nfterrax/repos params={'per_page': 100, 'page': 1}
DEBUG:__main__:GET_JSON https://api.github.com/users/carlcastanas/repos params={'per_page': 100, 'page': 1}
DEBUG:__main__:GET_JSON https://api.github.com/users/cepseu1/repos params={'per_page': 100, 'page': 1}
DEBUG:__main__:GET_JSON https://api.github.com/users/yandex/repos params={'per_page': 100, 'page': 1}
DEBUG:__main__:GET_JSON https://api.github.com/users/yandex/repos params={'per_page': 100, 'page': 2}
DEBUG:__main__:GET_JSON https://api.github.com/users/alexey-goloburdin/repos params={'per_page': 100, 'page': 1}
DEBUG:__main__:GET_JSON https://api.github.com/users/codersgyan/repos params={'per_page': 100, 'page': 1}
DEBUG:__main__:GET_JSON https://api.github.com/users/codersgyan/repos params={'per_page': 100, 'page': 2}
DEBUG:__main__:GET_JSON https://api.github.com/users/codersgyan/repos params={'per_page': 100, 'page': 3}
DEBUG:__main__:GET_JSON https://api.github.com/users/yandexdataschool/repos params={'per_page': 100, 'page': 1}
DEBUG:__main__:GET_JSON https://api.github.com/users/yandexdataschool/repos params={'per_page': 100, 'page': 2}
DEBUG:__main__:GET_JSON https://api.github.com/users/KEV0143/repos params={'per_page': 100, 'page': 1}
DEBUG:__main__:GET_JSON https://api.github.com/users/dstogov/repos params={'per_page': 100, 'page': 1}
DEBUG:__main__:GET_JSON https://api.github.com/users/Good4lien/repos params={'per_page': 100, 'page': 1}
DEBUG:__main__:GET_JSON https://api.github.com/users/sergeche/repos params={'per_page': 100, 'page': 1}
DEBUG:__main__:GET_JSON https://api.github.com/users/esokolov/repos params={'per_page': 100, 'page': 1}
DEBUG:__main__:GET_JSON https://api.github.com/users/Dmitriy-Vas/repos params={'per_page': 100, 'page': 1}
DEBUG:__main__:GET_JSON https://api.github.com/users/StanislavPetrovV/repos params={'per_page': 100, 'page': 1}
DEBUG:__main__:GET_JSON https://api.github.com/users/Bo0oM/repos params={'per_page': 100, 'page': 1}
DEBUG:__main__:GET_JSON https://api.github.com/users/grishka/repos params={'per_page': 100, 'page': 1}
DEBUG:__main__:GET_JSON https://api.github.com/users/mybatis/repos params={'per_page': 100, 'page': 1}
DEBUG:__main__:GET_JSON https://api.github.com/users/kmike/repos params={'per_page': 100, 'page': 1}
DEBUG:__main__:GET_JSON https://api.github.com/users/kmike/repos params={'per_page': 100, 'page': 2}
DEBUG:__main__:GET_JSON https://api.github.com/users/Dyakonov/repos params={'per_page': 100, 'page': 1}
DEBUG:__main__:GET_JSON https://api.github.com/users/alexander-akait/repos params={'per_page': 100, 'page': 1}
DEBUG:__main__:GET_JSON https://api.github.com/users/alexander-akait/repos params={'per_page': 100, 'page': 2}
DEBUG:__main__:GET_JSON https://api.github.com/users/antonkomarev/repos params={'per_page': 100, 'page': 1}
DEBUG:__main__:GET_JSON https://api.github.com/users/swabird/repos params={'per_page': 100, 'page': 1}
DEBUG:__main__:GET_JSON https://api.github.com/users/T8RIN/repos params={'per_page': 100, 'page': 1}
DEBUG:__main__:GET_JSON https://api.github.com/users/Prototik/repos params={'per_page': 100, 'page': 1}
DEBUG:__main__:GET_JSON https://api.github.com/users/enghamzasalem/repos params={'per_page': 100, 'page': 1}
DEBUG:__main__:GET_JSON https://api.github.com/users/enghamzasalem/repos params={'per_page': 100, 'page': 2}
DEBUG:__main__:GET_JSON https://api.github.com/users/nsf/repos params={'per_page': 100, 'page': 1}
DEBUG:__main__:GET_JSON https://api.github.com/users/klen/repos params={'per_page': 100, 'page': 1}
DEBUG:__main__:GET_JSON https://api.github.com/users/klen/repos params={'per_page': 100, 'page': 2}
DEBUG:__main__:GET_JSON https://api.github.com/users/extremecodetv/repos params={'per_page': 100, 'page': 1}
DEBUG:__main__:GET_JSON https://api.github.com/users/VKCOM/repos params={'per_page': 100, 'page': 1}
DEBUG:__main__:GET_JSON https://api.github.com/users/VKCOM/repos params={'per_page': 100, 'page': 2}
DEBUG:__main__:GET_JSON https://api.github.com/users/tigertv/repos params={'per_page': 100, 'page': 1}
DEBUG:__main__:GET_JSON https://api.github.com/users/number571/repos params={'per_page': 100, 'page': 1}
DEBUG:__main__:GET_JSON https://api.github.com/users/barancev/repos params={'per_page': 100, 'page': 1}
DEBUG:__main__:GET_JSON https://api.github.com/users/nshmyrev/repos params={'per_page': 100, 'page': 1}
DEBUG:__main__:GET_JSON https://api.github.com/users/istarkov/repos params={'per_page': 100, 'page': 1}
DEBUG:__main__:GET_JSON https://api.github.com/users/DosX-dev/repos params={'per_page': 100, 'page': 1}
DEBUG:__main__:GET_JSON https://api.github.com/users/tilir/repos params={'per_page': 100, 'page': 1}
DEBUG:__main__:GET_JSON https://api.github.com/users/lorien/repos params={'per_page': 100, 'page': 1}
DEBUG:__main__:GET_JSON https://api.github.com/users/dkurt/repos params={'per_page': 100, 'page': 1}
DEBUG:__main__:GET_JSON https://api.github.com/users/artdeell/repos params={'per_page': 100, 'page': 1}
DEBUG:__main__:GET_JSON https://api.github.com/users/FilimonovAlexey/repos params={'per_page': 100, 'page': 1}
DEBUG:__main__:GET_JSON https://api.github.com/users/vpisarev/repos params={'per_page': 100, 'page': 1}
DEBUG:__main__:GET_JSON https://api.github.com/users/4n70w4/repos params={'per_page': 100, 'page': 1}
DEBUG:__main__:GET_JSON https://api.github.com/users/bravekirty/repos params={'per_page': 100, 'page': 1}
DEBUG:__main__:GET_JSON https://api.github.com/users/bravekirty/repos params={'per_page': 100, 'page': 2}
DEBUG:__main__:GET_JSON https://api.github.com/users/milabs/repos params={'per_page': 100, 'page': 1}
DEBUG:__main__:GET_JSON https://api.github.com/users/AlexGladkov/repos params={'per_page': 100, 'page': 1}
DEBUG:__main__:GET_JSON https://api.github.com/users/anticensority/repos params={'per_page': 100, 'page': 1}
DEBUG:__main__:GET_JSON https://api.github.com/users/harryheman/repos params={'per_page': 100, 'page': 1}
DEBUG:__main__:GET_JSON https://api.github.com/users/tg-bomze/repos params={'per_page': 100, 'page': 1}
DEBUG:__main__:GET_JSON https://api.github.com/users/developer01234/repos params={'per_page': 100, 'page': 1}
DEBUG:__main__:GET_JSON https://api.github.com/users/Quarx2k/repos params={'per_page': 100, 'page': 1}
DEBUG:__main__:GET_JSON https://api.github.com/users/floatdrop/repos params={'per_page': 100, 'page': 1}
DEBUG:__main__:GET_JSON https://api.github.com/users/floatdrop/repos params={'per_page': 100, 'page': 2}
DEBUG:__main__:GET_JSON https://api.github.com/users/alalek/repos params={'per_page': 100, 'page': 1}
DEBUG:__main__:GET_JSON https://api.github.com/users/mrDIMAS/repos params={'per_page': 100, 'page': 1}
DEBUG:__main__:GET_JSON https://api.github.com/users/lisyarus/repos params={'per_page': 100, 'page': 1}
DEBUG:__main__:GET_JSON https://api.github.com/users/bb33bb/repos params={'per_page': 100, 'page': 1}
DEBUG:__main__:GET_JSON https://api.github.com/users/bb33bb/repos params={'per_page': 100, 'page': 2}
DEBUG:__main__:GET_JSON https://api.github.com/users/bb33bb/repos params={'per_page': 100, 'page': 3}
DEBUG:__main__:GET_JSON https://api.github.com/users/bb33bb/repos params={'per_page': 100, 'page': 4}
DEBUG:__main__:GET_JSON https://api.github.com/users/bb33bb/repos params={'per_page': 100, 'page': 5}
DEBUG:__main__:GET_JSON https://api.github.com/users/bb33bb/repos params={'per_page': 100, 'page': 6}
DEBUG:__main__:GET_JSON https://api.github.com/users/bb33bb/repos params={'per_page': 100, 'page': 7}
DEBUG:__main__:GET_JSON https://api.github.com/users/bb33bb/repos params={'per_page': 100, 'page': 8}
DEBUG:__main__:GET_JSON https://api.github.com/users/bb33bb/repos params={'per_page': 100, 'page': 9}
DEBUG:__main__:GET_JSON https://api.github.com/users/bb33bb/repos params={'per_page': 100, 'page': 10}
DEBUG:__main__:GET_JSON https://api.github.com/users/bb33bb/repos params={'per_page': 100, 'page': 11}
DEBUG:__main__:GET_JSON https://api.github.com/users/bb33bb/repos params={'per_page': 100, 'page': 12}
DEBUG:__main__:GET_JSON https://api.github.com/users/bb33bb/repos params={'per_page': 100, 'page': 13}
DEBUG:__main__:GET_JSON https://api.github.com/users/bb33bb/repos params={'per_page': 100, 'page': 14}
DEBUG:__main__:GET_JSON https://api.github.com/users/bb33bb/repos params={'per_page': 100, 'page': 15}
DEBUG:__main__:GET_JSON https://api.github.com/users/bb33bb/repos params={'per_page': 100, 'page': 16}
DEBUG:__main__:GET_JSON https://api.github.com/users/bb33bb/repos params={'per_page': 100, 'page': 17}
DEBUG:__main__:GET_JSON https://api.github.com/users/bb33bb/repos params={'per_page': 100, 'page': 18}
DEBUG:__main__:GET_JSON https://api.github.com/users/bb33bb/repos params={'per_page': 100, 'page': 19}
DEBUG:__main__:GET_JSON https://api.github.com/users/bb33bb/repos params={'per_page': 100, 'page': 20}
DEBUG:__main__:GET_JSON https://api.github.com/users/bb33bb/repos params={'per_page': 100, 'page': 21}
DEBUG:__main__:GET_JSON https://api.github.com/users/bb33bb/repos params={'per_page': 100, 'page': 22}
DEBUG:__main__:GET_JSON https://api.github.com/users/bb33bb/repos params={'per_page': 100, 'page': 23}
DEBUG:__main__:GET_JSON https://api.github.com/users/bb33bb/repos params={'per_page': 100, 'page': 24}
DEBUG:__main__:GET_JSON https://api.github.com/users/bb33bb/repos params={'per_page': 100, 'page': 25}
DEBUG:__main__:GET_JSON https://api.github.com/users/bb33bb/repos params={'per_page': 100, 'page': 26}
DEBUG:__main__:GET_JSON https://api.github.com/users/bb33bb/repos params={'per_page': 100, 'page': 27}
DEBUG:__main__:GET_JSON https://api.github.com/users/bb33bb/repos params={'per_page': 100, 'page': 28}
DEBUG:__main__:GET_JSON https://api.github.com/users/bb33bb/repos params={'per_page': 100, 'page': 29}
DEBUG:__main__:GET_JSON https://api.github.com/users/bb33bb/repos params={'per_page': 100, 'page': 30}
DEBUG:__main__:GET_JSON https://api.github.com/users/bb33bb/repos params={'per_page': 100, 'page': 31}
DEBUG:__main__:REPOS_REQ 100
DEBUG:__main__:GET_JSON https://api.github.com/users/bb33bb/repos params={'per_page': 100, 'page': 32}
DEBUG:__main__:GET_JSON https://api.github.com/users/bb33bb/repos params={'per_page': 100, 'page': 33}
DEBUG:__main__:GET_JSON https://api.github.com/users/bb33bb/repos params={'per_page': 100, 'page': 34}
DEBUG:__main__:GET_JSON https://api.github.com/users/bb33bb/repos params={'per_page': 100, 'page': 35}
DEBUG:__main__:GET_JSON https://api.github.com/users/bb33bb/repos params={'per_page': 100, 'page': 36}
DEBUG:__main__:GET_JSON https://api.github.com/users/bb33bb/repos params={'per_page': 100, 'page': 37}
DEBUG:__main__:GET_JSON https://api.github.com/users/bb33bb/repos params={'per_page': 100, 'page': 38}
DEBUG:__main__:GET_JSON https://api.github.com/users/bb33bb/repos params={'per_page': 100, 'page': 39}
DEBUG:__main__:GET_JSON https://api.github.com/users/bb33bb/repos params={'per_page': 100, 'page': 40}
DEBUG:__main__:GET_JSON https://api.github.com/users/bb33bb/repos params={'per_page': 100, 'page': 41}
DEBUG:__main__:GET_JSON https://api.github.com/users/bb33bb/repos params={'per_page': 100, 'page': 42}
DEBUG:__main__:GET_JSON https://api.github.com/users/bb33bb/repos params={'per_page': 100, 'page': 43}
DEBUG:__main__:GET_JSON https://api.github.com/users/bb33bb/repos params={'per_page': 100, 'page': 44}
DEBUG:__main__:GET_JSON https://api.github.com/users/bb33bb/repos params={'per_page': 100, 'page': 45}
DEBUG:__main__:GET_JSON https://api.github.com/users/bb33bb/repos params={'per_page': 100, 'page': 46}
DEBUG:__main__:GET_JSON https://api.github.com/users/bb33bb/repos params={'per_page': 100, 'page': 47}
DEBUG:__main__:GET_JSON https://api.github.com/users/aleksanderlamkov/repos params={'per_page': 100, 'page': 1}
DEBUG:__main__:GET_JSON https://api.github.com/users/shwanoff/repos params={'per_page': 100, 'page': 1}
DEBUG:__main__:GET_JSON https://api.github.com/users/MzHmO/repos params={'per_page': 100, 'page': 1}
DEBUG:__main__:GET_JSON https://api.github.com/users/VladimirBalun/repos params={'per_page': 100, 'page': 1}
DEBUG:__main__:GET_JSON https://api.github.com/users/ellen-simonyan/repos params={'per_page': 100, 'page': 1}
DEBUG:__main__:GET_JSON https://api.github.com/users/TheAndreyZakharov/repos params={'per_page': 100, 'page': 1}
DEBUG:__main__:GET_JSON https://api.github.com/users/KANKOSHEV/repos params={'per_page': 100, 'page': 1}
DEBUG:__main__:GET_JSON https://api.github.com/users/Irina-Smol/repos params={'per_page': 100, 'page': 1}
DEBUG:__main__:GET_JSON https://api.github.com/users/veged/repos params={'per_page': 100, 'page': 1}
DEBUG:__main__:GET_JSON https://api.github.com/users/enhorse/repos params={'per_page': 100, 'page': 1}
DEBUG:__main__:GET_JSON https://api.github.com/users/Kerminator1973/repos params={'per_page': 100, 'page': 1}
DEBUG:__main__:GET_JSON https://api.github.com/users/nikita-volkov/repos params={'per_page': 100, 'page': 1}
DEBUG:__main__:GET_JSON https://api.github.com/users/nikita-volkov/repos params={'per_page': 100, 'page': 2}
DEBUG:__main__:GET_JSON https://api.github.com/users/nikita-volkov/repos params={'per_page': 100, 'page': 3}
DEBUG:__main__:GET_JSON https://api.github.com/users/kolyvan/repos params={'per_page': 100, 'page': 1}
DEBUG:__main__:GET_JSON https://api.github.com/users/shivaya-dav/repos params={'per_page': 100, 'page': 1}
DEBUG:__main__:GET_JSON https://api.github.com/users/ozkriff/repos params={'per_page': 100, 'page': 1}
DEBUG:__main__:GET_JSON https://api.github.com/users/Domaman202/repos params={'per_page': 100, 'page': 1}
DEBUG:__main__:GET_JSON https://api.github.com/users/poma/repos params={'per_page': 100, 'page': 1}
DEBUG:__main__:GET_JSON https://api.github.com/users/poma/repos params={'per_page': 100, 'page': 2}
DEBUG:__main__:GET_JSON https://api.github.com/users/HopelessCompass/repos params={'per_page': 100, 'page': 1}
DEBUG:__main__:GET_JSON https://api.github.com/users/timscriptov/repos params={'per_page': 100, 'page': 1}
DEBUG:__main__:GET_JSON https://api.github.com/users/maxlapshin/repos params={'per_page': 100, 'page': 1}
DEBUG:__main__:GET_JSON https://api.github.com/users/peterarsentev/repos params={'per_page': 100, 'page': 1}
DEBUG:__main__:GET_JSON https://api.github.com/users/Friend-LGA/repos params={'per_page': 100, 'page': 1}
DEBUG:__main__:GET_JSON https://api.github.com/users/alexander-ladygin/repos params={'per_page': 100, 'page': 1}
DEBUG:__main__:GET_JSON https://api.github.com/users/catamphetamine/repos params={'per_page': 100, 'page': 1}
DEBUG:__main__:GET_JSON https://api.github.com/users/mrmlnc/repos params={'per_page': 100, 'page': 1}
DEBUG:__main__:GET_JSON https://api.github.com/users/Blueberryy/repos params={'per_page': 100, 'page': 1}
DEBUG:__main__:GET_JSON https://api.github.com/users/Blueberryy/repos params={'per_page': 100, 'page': 2}
DEBUG:__main__:GET_JSON https://api.github.com/users/Blueberryy/repos params={'per_page': 100, 'page': 3}
DEBUG:__main__:GET_JSON https://api.github.com/users/Blueberryy/repos params={'per_page': 100, 'page': 4}
DEBUG:__main__:GET_JSON https://api.github.com/users/Blueberryy/repos params={'per_page': 100, 'page': 5}
DEBUG:__main__:GET_JSON https://api.github.com/users/Blueberryy/repos params={'per_page': 100, 'page': 6}
DEBUG:__main__:GET_JSON https://api.github.com/users/Blueberryy/repos params={'per_page': 100, 'page': 7}
DEBUG:__main__:GET_JSON https://api.github.com/users/ldpreload/repos params={'per_page': 100, 'page': 1}
DEBUG:__main__:GET_JSON https://api.github.com/users/monosans/repos params={'per_page': 100, 'page': 1}
DEBUG:__main__:GET_JSON https://api.github.com/users/vlasovskikh/repos params={'per_page': 100, 'page': 1}
DEBUG:__main__:GET_JSON https://api.github.com/users/VladislavEremeev/repos params={'per_page': 100, 'page': 1}
DEBUG:__main__:GET_JSON https://api.github.com/users/Nashatyrev/repos params={'per_page': 100, 'page': 1}
DEBUG:__main__:GET_JSON https://api.github.com/users/TotallyNotAHaxxer/repos params={'per_page': 100, 'page': 1}
DEBUG:__main__:GET_JSON https://api.github.com/users/TotallyNotAHaxxer/repos params={'per_page': 100, 'page': 2}
DEBUG:__main__:GET_JSON https://api.github.com/users/maxzaikin/repos params={'per_page': 100, 'page': 1}
DEBUG:__main__:GET_JSON https://api.github.com/users/SoberGrim/repos params={'per_page': 100, 'page': 1}
DEBUG:__main__:GET_JSON https://api.github.com/users/cepseu6/repos params={'per_page': 100, 'page': 1}
DEBUG:__main__:GET_JSON https://api.github.com/users/ilyhalight/repos params={'per_page': 100, 'page': 1}
DEBUG:__main__:GET_JSON https://api.github.com/users/TheNewAttacker64/repos params={'per_page': 100, 'page': 1}
DEBUG:__main__:GET_JSON https://api.github.com/users/darkk/repos params={'per_page': 100, 'page': 1}
DEBUG:__main__:GET_JSON https://api.github.com/users/DmitryTsepelev/repos params={'per_page': 100, 'page': 1}
DEBUG:__main__:GET_JSON https://api.github.com/users/jkenix/repos params={'per_page': 100, 'page': 1}
DEBUG:__main__:GET_JSON https://api.github.com/users/PawelStepanov/repos params={'per_page': 100, 'page': 1}
DEBUG:__main__:GET_JSON https://api.github.com/users/tigr1234566/repos params={'per_page': 100, 'page': 1}
DEBUG:__main__:GET_JSON https://api.github.com/users/Skeltex/repos params={'per_page': 100, 'page': 1}
DEBUG:__main__:GET_JSON https://api.github.com/users/nukeykt/repos params={'per_page': 100, 'page': 1}
DEBUG:__main__:GET_JSON https://api.github.com/users/grafov/repos params={'per_page': 100, 'page': 1}
DEBUG:__main__:GET_JSON https://api.github.com/users/grafov/repos params={'per_page': 100, 'page': 2}
DEBUG:__main__:GET_JSON https://api.github.com/users/seregazhuk/repos params={'per_page': 100, 'page': 1}
DEBUG:__main__:GET_JSON https://api.github.com/users/pauljamm/repos params={'per_page': 100, 'page': 1}
DEBUG:__main__:GET_JSON https://api.github.com/users/aemeltsev/repos params={'per_page': 100, 'page': 1}
DEBUG:__main__:GET_JSON https://api.github.com/users/CODeRUS/repos params={'per_page': 100, 'page': 1}
DEBUG:__main__:GET_JSON https://api.github.com/users/CODeRUS/repos params={'per_page': 100, 'page': 2}
DEBUG:__main__:GET_JSON https://api.github.com/users/ddemidov/repos params={'per_page': 100, 'page': 1}
DEBUG:__main__:GET_JSON https://api.github.com/users/webmakaka/repos params={'per_page': 100, 'page': 1}
DEBUG:__main__:GET_JSON https://api.github.com/users/webmakaka/repos params={'per_page': 100, 'page': 2}
DEBUG:__main__:GET_JSON https://api.github.com/users/funny-falcon/repos params={'per_page': 100, 'page': 1}
DEBUG:__main__:GET_JSON https://api.github.com/users/funny-falcon/repos params={'per_page': 100, 'page': 2}
DEBUG:__main__:GET_JSON https://api.github.com/users/ac3ss0r/repos params={'per_page': 100, 'page': 1}
DEBUG:__main__:GET_JSON https://api.github.com/users/kushti/repos params={'per_page': 100, 'page': 1}
DEBUG:__main__:GET_JSON https://api.github.com/users/EvilBeaver/repos params={'per_page': 100, 'page': 1}
DEBUG:__main__:GET_JSON https://api.github.com/users/pConst/repos params={'per_page': 100, 'page': 1}
DEBUG:__main__:GET_JSON https://api.github.com/users/NekR/repos params={'per_page': 100, 'page': 1}
DEBUG:__main__:GET_JSON https://api.github.com/users/I-Atlas/repos params={'per_page': 100, 'page': 1}
DEBUG:__main__:GET_JSON https://api.github.com/users/artpolikarpov/repos params={'per_page': 100, 'page': 1}
DEBUG:__main__:GET_JSON https://api.github.com/users/crashmax-dev/repos params={'per_page': 100, 'page': 1}

,id,node_id,name,full_name,private,html_url,description,fork,url,forks_url,...,license_name,license_spdx_id,license_url,license_node_id,permissions_admin,permissions_maintain,permissions_push,permissions_triage,permissions_pull,license
0,515339264,R_kgDOHrd0AA,agonist,Kwynto/agonist,False,https://github.com/Kwynto/agonist,A program for checking and maintaining an awes...,False,https://api.github.com/repos/Kwynto/agonist,https://api.github.com/repos/Kwynto/agonist/forks,...,MIT License,MIT,https://api.github.com/licenses/mit,MDc6TGljZW5zZTEz,False,False,False,False,True,NaN
1,471783700,R_kgDOHB7ZFA,awesome-go,Kwynto/awesome-go,False,https://github.com/Kwynto/awesome-go,"A curated list of awesome Go frameworks, libra...",True,https://api.github.com/repos/Kwynto/awesome-go,https://api.github.com/repos/Kwynto/awesome-go...,...,MIT License,MIT,https://api.github.com/licenses/mit,MDc6TGljZW5zZTEz,False,False,False,False,True,NaN
2,672090323,R_kgDOKA9I0w,base-folders-go,Kwynto/base-folders-go,False,https://github.com/Kwynto/base-folders-go,This is a simple repository with base folders ...,False,https://api.github.com/repos/Kwynto/base-folde...,https://api.github.com/repos/Kwynto/base-folde...,...,NaN,NaN,NaN,NaN,False,False,False,False,True,NaN
3,773330026,R_kgDOLhgUag,colorable,Kwynto/colorable,False,https://github.com/Kwynto/colorable,Colorable writer for windows.,False,https://api.github.com/repos/Kwynto/colorable,https://api.github.com/repos/Kwynto/colorable/...,...,MIT License,MIT,https://api.github.com/licenses/mit,MDc6TGljZW5zZTEz,False,False,False,False,True,NaN
4,674351858,R_kgDOKDHK8g,exps-and-tests,Kwynto/exps-and-tests,False,https://github.com/Kwynto/exps-and-tests,This is an experimental repository,False,https://api.github.com/repos/Kwynto/exps-and-t...,https://api.github.com/repos/Kwynto/exps-and-t...,...,NaN,NaN,NaN,NaN,False,False,False,False,True,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69936,604986151,R_kgDOJA9bJw,simple_calculator,labdmitriy/simple_calculator,False,https://github.com/labdmitriy/simple_calculator,A basic calculator written in Python used to t...,True,https://api.github.com/repos/labdmitriy/simple...,https://api.github.com/repos/labdmitriy/simple...,...,MIT License,MIT,https://api.github.com/licenses/mit,MDc6TGljZW5zZTEz,False,False,False,False,True,NaN
69937,745476462,R_kgDOLG8Rbg,tavily-python,labdmitriy/tavily-python,False,https://github.com/labdmitriy/tavily-python,A python wrapper for Tavily search API,True,https://api.github.com/repos/labdmitriy/tavily...,https://api.github.com/repos/labdmitriy/tavily...,...,MIT License,MIT,https://api.github.com/licenses/mit,MDc6TGljZW5zZTEz,False,False,False,False,True,NaN
69938,271366391,MDEwOlJlcG9zaXRvcnkyNzEzNjYzOTE=,telegram_interactions,labdmitriy/telegram_interactions,False,https://github.com/labdmitriy/telegram_interac...,None,False,https://api.github.com/repos/labdmitriy/telegr...,https://api.github.com/repos/labdmitriy/telegr...,...,NaN,NaN,NaN,NaN,False,False,False,False,True,NaN
69939,371024975,MDEwOlJlcG9zaXRvcnkzNzEwMjQ5NzU=,the-hat-game,labdmitriy/the-hat-game,False,https://github.com/labdmitriy/the-hat-game,Learn word embedding and service deployment by...,True,https://api.github.com/repos/labdmitriy/the-ha...,https://api.github.com/repos/labdmitriy/the-ha...,...,NaN,NaN,NaN,NaN,False,False,False,False,True,NaN
69940,591989766,R_kgDOI0kMBg,writing-faster-python3,labdmitriy/writing-faster-python3,False,https://github.com/labdmitriy/writing-faster-p...,Code examples for the writing faster Python 3 ...,True,https://api.github.com/repos/labdmitriy/writin...,https://api.github.com/repos/labdmitriy/writin...,...,MIT License,MIT,https://api.github.com/licenses/mit,MDc6TGljZW5zZTEz,False,False,False,False,True,NaN

In [3]:
rows = []
with open("repos.jsonl", encoding="utf-8") as f:
    for line in f:
        rows.append(json.loads(line))
df_repos = pd.json_normalize(rows, sep="_")

In [4]:
def dec(s):
    if not s:
        return None
    return base64.b64decode(s.replace("\n", "")).decode("utf-8", errors="replace")

df_repos_enriched = df_repos.copy()
prev = {}
if os.path.isfile("repos_enriched.jsonl"):
    with open("repos_enriched.jsonl", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                d = json.loads(line)
            except json.JSONDecodeError:
                continue
            k = d.get("full_name")
            if k:
                prev[k] = d
df_repos_enriched["readme"] = None
df_repos_enriched["lang_bytes"] = None
df_repos_enriched["lang_pct"] = None
req_n = 0
for i in df_repos_enriched.index:
    fn = df_repos_enriched.at[i, "full_name"]
    if fn in prev:
        o = prev[fn]
        df_repos_enriched.at[i, "readme"] = o.get("readme")
        df_repos_enriched.at[i, "lang_bytes"] = o.get("lang_bytes")
        df_repos_enriched.at[i, "lang_pct"] = o.get("lang_pct")
        continue
    try:
        r = get_json(f"https://api.github.com/repos/{fn}/readme")
        if r.status_code == 200:
            j = r.json()
            df_repos_enriched.at[i, "readme"] = dec(j.get("content", None))
        r = get_json(f"https://api.github.com/repos/{fn}/languages")
        if r.status_code == 200:
            lb = r.json()
            df_repos_enriched.at[i, "lang_bytes"] = lb
            t = sum(lb.values())
            if t > 0:
                df_repos_enriched.at[i, "lang_pct"] = {k: 100.0 * v / t for k, v in lb.items()}
            else:
                df_repos_enriched.at[i, "lang_pct"] = {}
        else:
            df_repos_enriched.at[i, "lang_bytes"] = None
            df_repos_enriched.at[i, "lang_pct"] = None
    except (ValueError, AttributeError, TypeError):
        df_repos_enriched.at[i, "readme"] = None
        df_repos_enriched.at[i, "lang_bytes"] = None
        df_repos_enriched.at[i, "lang_pct"] = None
    with open("repos_enriched.jsonl", "a", encoding="utf-8") as f:
        f.write(df_repos_enriched.loc[[i]].to_json(orient="records", lines=True) + "\n")
    req_n += 1
    if req_n % 100 == 0:
        logger.debug(f"ENRICH_REQ {req_n}")

df_repos_enriched

Streaming output truncated to the last 5000 lines.
DEBUG:__main__:GET_JSON https://api.github.com/repos/Bulvinkoln/GU_Practic_3567/readme params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/Bulvinkoln/GU_Practic_3567/languages params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/Bulvinkoln/Home_Work/readme params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/Bulvinkoln/Home_Work/languages params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/Bulvinkoln/JavaScript_Practice/readme params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/Bulvinkoln/JavaScript_Practice/languages params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/Bulvinkoln/js-fundamenrals-tasks/readme params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/Bulvinkoln/js-fundamenrals-tasks/languages params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/Bulvinkoln/jstdg7/readme params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/Bulvinkoln/jstdg7/languages params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/Bulvinkoln/JS_task_answers/readme params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/Bulvinkoln/JS_task_answers/languages params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/Bulvinkoln/MyCostGB/readme params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/Bulvinkoln/MyCostGB/languages params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/Bulvinkoln/OriginSeminar_16.06.2022/readme params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/Bulvinkoln/OriginSeminar_16.06.2022/languages params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/Bulvinkoln/OriginTest_26.08.2022/readme params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/Bulvinkoln/OriginTest_26.08.2022/languages params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/Bulvinkoln/Origin_14.07.22/readme params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/Bulvinkoln/Origin_14.07.22/languages params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/Bulvinkoln/Origin_16.07.22/readme params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/Bulvinkoln/Origin_16.07.22/languages params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/Bulvinkoln/Origin_18.06.2022/readme params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/Bulvinkoln/Origin_18.06.2022/languages params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/Bulvinkoln/Practic_3979/readme params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/Bulvinkoln/Practic_3979/languages params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/Bulvinkoln/Practic_group/readme params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/Bulvinkoln/Practic_group/languages params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/Bulvinkoln/Product_3977/readme params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/Bulvinkoln/Product_3977/languages params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/Bulvinkoln/Project/readme params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/Bulvinkoln/Project/languages params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/Bulvinkoln/Project_3612/readme params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/Bulvinkoln/Project_3612/languages params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/Bulvinkoln/PullFirst/readme params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/Bulvinkoln/PullFirst/languages params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/Bulvinkoln/repos/readme params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/Bulvinkoln/repos/languages params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/Bulvinkoln/Seminar_29.05.2022/readme params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/Bulvinkoln/Seminar_29.05.2022/languages params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/Bulvinkoln/SEM_Origin_01.07.2022/readme params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/Bulvinkoln/SEM_Origin_01.07.2022/languages params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/Bulvinkoln/SEM_origin_02.07.2022/readme params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/Bulvinkoln/SEM_origin_02.07.2022/languages params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/Bulvinkoln/stryuret/readme params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/Bulvinkoln/stryuret/languages params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/Bulvinkoln/Team_3978/readme params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/Bulvinkoln/Team_3978/languages params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/Bulvinkoln/Team_4049/readme params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/Bulvinkoln/Team_4049/languages params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/Bulvinkoln/Team_4051/readme params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/Bulvinkoln/Team_4051/languages params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/Bulvinkoln/Test_08.09.2022/readme params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/Bulvinkoln/Test_08.09.2022/languages params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/Bulvinkoln/Test_git/readme params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/Bulvinkoln/Test_git/languages params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/Bulvinkoln/TypeScript/readme params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/Bulvinkoln/TypeScript/languages params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/-algorithms_2021/readme params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/-algorithms_2021/languages params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/aiobot/readme params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/aiobot/languages params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/algorithms_2022/readme params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/algorithms_2022/languages params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/app_stock_system/readme params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/app_stock_system/languages params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/autotests/readme params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/autotests/languages params=None
DEBUG:__main__:ENRICH_REQ 19000
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/bewelder_redesign/readme params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/bewelder_redesign/languages params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/bot_test/readme params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/bot_test/languages params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/db_project_metrology_expertise/readme params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/db_project_metrology_expertise/languages params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/dj_main/readme params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/dj_main/languages params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/dj_pyany/readme params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/dj_pyany/languages params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/dj_test/readme params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/dj_test/languages params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/fastapi_depl/readme params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/fastapi_depl/languages params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/fastapi_depl_test/readme params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/fastapi_depl_test/languages params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/fast_api_febr/readme params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/fast_api_febr/languages params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/FitClubBot/readme params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/FitClubBot/languages params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/flask-hello-world/readme params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/flask-hello-world/languages params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/flask_deploy/readme params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/flask_deploy/languages params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/flask_deploy_parser/readme params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/flask_deploy_parser/languages params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/flask_prj/readme params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/flask_prj/languages params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/flask_prj_oct/readme params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/flask_prj_oct/languages params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/flask_sept/readme params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/flask_sept/languages params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/foamyQuadMesh_generator/readme params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/foamyQuadMesh_generator/languages params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/foodgram-project/readme params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/foodgram-project/languages params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/foodgram-project-di/readme params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/foodgram-project-di/languages params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/foodgram-project_corr/readme params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/foodgram-project_corr/languages params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/gbvueshop/readme params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/gbvueshop/languages params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/gbvueshop_api/readme params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/gbvueshop_api/languages params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/GB_architectures_design_patterns/readme params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/GB_architectures_design_patterns/languages params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/git-repo/readme params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/git-repo/languages params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/hh_new/readme params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/hh_new/languages params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/hh_p/readme params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/hh_p/languages params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/hh_parser/readme params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/hh_parser/languages params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/hh_parser_deploy_jan/readme params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/hh_parser_deploy_jan/languages params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/hh_parser_febr/readme params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/hh_parser_febr/languages params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/hh_parser_version_1/readme params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/hh_parser_version_1/languages params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/hotel-management/readme params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/hotel-management/languages params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/Interview/readme params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/Interview/languages params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/kirill-marketcapov/readme params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/kirill-marketcapov/languages params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/market_demo/readme params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/market_demo/languages params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/market_prj/readme params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/market_prj/languages params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/market_prj_deploy/readme params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/market_prj_deploy/languages params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/market_prj_render/readme params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/market_prj_render/languages params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/market_rend/readme params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/market_rend/languages params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/max-dtel-bot/readme params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/max-dtel-bot/languages params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/MediaBot/readme params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/MediaBot/languages params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/mesh_generator/readme params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/mesh_generator/languages params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/monday/readme params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/monday/languages params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/MSiODiSI/readme params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/MSiODiSI/languages params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/myproject/readme params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/myproject/languages params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/Need_For_Feed/readme params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/Need_For_Feed/languages params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/Netology_Vkinder_Bot/readme params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/Netology_Vkinder_Bot/languages params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/new_flask_blog/readme params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/new_flask_blog/languages params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/new_test/readme params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/new_test/languages params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/OpenFOAM_decompose_GUI/readme params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/OpenFOAM_decompose_GUI/languages params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/OpenFOAM_GUI/readme params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/OpenFOAM_GUI/languages params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/OpenFOAM_GUI_v1/readme params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/OpenFOAM_GUI_v1/languages params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/openfoam_mesh_app/readme params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/openfoam_mesh_app/languages params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/OpenFOAM_mesh_builder/readme params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/OpenFOAM_mesh_builder/languages params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/OpenFOAM_mirror_mesh/readme params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/OpenFOAM_mirror_mesh/languages params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/Pipe_turbulence_generation/readme params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/Pipe_turbulence_generation/languages params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/plaindjango/readme params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/plaindjango/languages params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/Planner/readme params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/Planner/languages params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/prj_deploy/readme params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/prj_deploy/languages params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/prj_for_deploy/readme params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/prj_for_deploy/languages params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/prj_pycharm/readme params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/prj_pycharm/languages params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/project/readme params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/project/languages params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/Python-interview/readme params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/Python-interview/languages params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/Python_Algos/readme params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/Python_Algos/languages params=None
DEBUG:__main__:GET_JSON https://api.github.com/repos/DmitryChitalov/python_algos_gb/readme params=None

,id,node_id,name,full_name,private,html_url,description,fork,url,forks_url,...,license_node_id,permissions_admin,permissions_maintain,permissions_push,permissions_triage,permissions_pull,license,readme,lang_bytes,lang_pct
0,515339264,R_kgDOHrd0AA,agonist,Kwynto/agonist,False,https://github.com/Kwynto/agonist,A program for checking and maintaining an awes...,False,https://api.github.com/repos/Kwynto/agonist,https://api.github.com/repos/Kwynto/agonist/forks,...,MDc6TGljZW5zZTEz,False,False,False,False,True,NaN,# AGonist\nA program for checking and maintain...,{'Go': 14480},{'Go': 100.0}
1,471783700,R_kgDOHB7ZFA,awesome-go,Kwynto/awesome-go,False,https://github.com/Kwynto/awesome-go,"A curated list of awesome Go frameworks, libra...",True,https://api.github.com/repos/Kwynto/awesome-go,https://api.github.com/repos/Kwynto/awesome-go...,...,MDc6TGljZW5zZTEz,False,False,False,False,True,NaN,"# Awesome Go\n\n<a href=""https://awesome-go.co...",{'Go': 26344},{'Go': 100.0}
2,672090323,R_kgDOKA9I0w,base-folders-go,Kwynto/base-folders-go,False,https://github.com/Kwynto/base-folders-go,This is a simple repository with base folders ...,False,https://api.github.com/repos/Kwynto/base-folde...,https://api.github.com/repos/Kwynto/base-folde...,...,NaN,False,False,False,False,True,NaN,# name repository \n\nThis is a simple reposit...,{'Go': 34},{'Go': 100.0}
3,773330026,R_kgDOLhgUag,colorable,Kwynto/colorable,False,https://github.com/Kwynto/colorable,Colorable writer for windows.,False,https://api.github.com/repos/Kwynto/colorable,https://api.github.com/repos/Kwynto/colorable/...,...,MDc6TGljZW5zZTEz,False,False,False,False,True,NaN,# colorable\n\nThis is a fork of the project g...,"{'Go': 29231, 'Shell': 273}","{'Go': 99.0747017354, 'Shell': 0.9252982646}"
4,674351858,R_kgDOKDHK8g,exps-and-tests,Kwynto/exps-and-tests,False,https://github.com/Kwynto/exps-and-tests,This is an experimental repository,False,https://api.github.com/repos/Kwynto/exps-and-t...,https://api.github.com/repos/Kwynto/exps-and-t...,...,NaN,False,False,False,False,True,NaN,# exps-and-tests\nThis is an experimental repo...,"{'Go': 154687, 'CSS': 49298, 'HTML': 41696, 'P...","{'Go': 62.4594201728, 'CSS': 19.9055156263, 'H..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69936,604986151,R_kgDOJA9bJw,simple_calculator,labdmitriy/simple_calculator,False,https://github.com/labdmitriy/simple_calculator,A basic calculator written in Python used to t...,True,https://api.github.com/repos/labdmitriy/simple...,https://api.github.com/repos/labdmitriy/simple...,...,MDc6TGljZW5zZTEz,False,False,False,False,True,NaN,# SimpleCalculator\n\nA basic calculator writt...,"{'Python': 7242, 'Makefile': 2314}","{'Python': 75.78484721640854, 'Makefile': 24.2..."
69937,745476462,R_kgDOLG8Rbg,tavily-python,labdmitriy/tavily-python,False,https://github.com/labdmitriy/tavily-python,A python wrapper for Tavily search API,True,https://api.github.com/repos/labdmitriy/tavily...,https://api.github.com/repos/labdmitriy/tavily...,...,MDc6TGljZW5zZTEz,False,False,False,False,True,NaN,=======================\nTavily Python Wrapper...,{'Python': 6581},{'Python': 100.0}
69938,271366391,MDEwOlJlcG9zaXRvcnkyNzEzNjYzOTE=,telegram_interactions,labdmitriy/telegram_interactions,False,https://github.com/labdmitriy/telegram_interac...,None,False,https://api.github.com/repos/labdmitriy/telegr...,https://api.github.com/repos/labdmitriy/telegr...,...,NaN,False,False,False,False,True,NaN,"# Библиотека для Домашнего задания 3 (""Обработ...",{'Python': 9663},{'Python': 100.0}
69939,371024975,MDEwOlJlcG9zaXRvcnkzNzEwMjQ5NzU=,the-hat-game,labdmitriy/the-hat-game,False,https://github.com/labdmitriy/the-hat-game,Learn word embedding and service deployment by...,True,https://api.github.com/repos/labdmitriy/the-ha...,https://api.github.com/repos/labdmitriy/the-ha...,...,NaN,False,False,False,False,True,NaN,# Игра в шляпу\n\nВам предлагается поучаствова...,"{'Jupyter Notebook': 121815, 'Python': 3804, '...","{'Jupyter Notebook': 95.38108586372677, 'Pytho..."
69940,591989766,R_kgDOI0kMBg,writing-faster-python3,labdmitriy/writing-faster-python3,False,https://github.com/labdmitriy/writing-faster-p...,Code examples for the writing faster Python 3 ...,True,https://api.github.com/repos/labdmitriy/writin...,https://api.github.com/repos/labdmitriy/writin...,...,MDc6TGljZW5zZTEz,False,False,False,False,True,NaN,# Writing Faster Python 3\n\n## Code examples\...,"{'Python': 27468, 'Shell': 2636, 'Roff': 1480}","{'Python': 86.96808510638297, 'Shell': 8.34599..."

In [12]:
# rows = []
# with open("repos_enriched.jsonl", encoding="utf-8") as f:
#     for line in f:
#         try:
#             rows.append(json.loads(line))
#         except json.JSONDecodeError:
#             continue

# df_repos_enriched = pd.json_normalize(rows, sep="_")

In [18]:
cols_r = [
    "sample_user_login", "id", "name", "full_name", "html_url",
    "description", "fork", "private", "archived", "disabled",
    "owner_login", "owner_type",
    "language", "topics", "license_spdx_id", "license_name",
    "stargazers_count", "forks_count", "watchers_count", "open_issues_count",
    "size", "created_at", "updated_at", "pushed_at",
    "default_branch", "visibility",
    "readme",
    "lang_bytes", "lang_pct",
]
df_repos_filtered = df_repos_enriched[[c for c in cols_r if c in df_repos_enriched.columns]]
df_repos_filtered

,sample_user_login,id,name,full_name,html_url,description,fork,private,archived,disabled,...,open_issues_count,size,created_at,updated_at,pushed_at,default_branch,visibility,readme,lang_bytes,lang_pct
0,Kwynto,515339264,agonist,Kwynto/agonist,https://github.com/Kwynto/agonist,A program for checking and maintaining an awes...,False,False,False,False,...,0,125,2022-07-18T20:58:12Z,2026-04-01T19:12:49Z,2024-07-31T19:33:11Z,main,public,# AGonist\nA program for checking and maintain...,"{""Go"": 14480}","{""Go"": 100.0}"
1,Kwynto,471783700,awesome-go,Kwynto/awesome-go,https://github.com/Kwynto/awesome-go,"A curated list of awesome Go frameworks, libra...",True,False,False,False,...,0,10576,2022-03-19T18:43:37Z,2026-01-21T09:31:53Z,2025-11-30T04:48:42Z,main,public,"# Awesome Go\n\n<a href=""https://awesome-go.co...","{""Go"": 26344}","{""Go"": 100.0}"
2,Kwynto,672090323,base-folders-go,Kwynto/base-folders-go,https://github.com/Kwynto/base-folders-go,This is a simple repository with base folders ...,False,False,False,False,...,0,2,2023-07-28T22:47:06Z,2026-01-21T09:38:33Z,2024-07-31T19:31:56Z,main,public,# name repository \n\nThis is a simple reposit...,"{""Go"": 34}","{""Go"": 100.0}"
3,Kwynto,773330026,colorable,Kwynto/colorable,https://github.com/Kwynto/colorable,Colorable writer for windows.,False,False,False,False,...,0,9,2024-03-17T11:30:47Z,2026-01-21T09:44:26Z,2024-03-17T12:07:31Z,main,public,# colorable\n\nThis is a fork of the project g...,"{""Go"": 29231, ""Shell"": 273}","{""Go"": 99.0747017354, ""Shell"": 0.9252982646}"
4,Kwynto,674351858,exps-and-tests,Kwynto/exps-and-tests,https://github.com/Kwynto/exps-and-tests,This is an experimental repository,False,False,False,False,...,0,334,2023-08-03T18:27:13Z,2026-01-21T09:38:39Z,2024-01-04T08:21:43Z,main,public,# exps-and-tests\nThis is an experimental repo...,"{""Go"": 154687, ""CSS"": 49298, ""HTML"": 41696, ""P...","{""Go"": 62.4594201728, ""CSS"": 19.9055156263, ""H..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69936,labdmitriy,604986151,simple_calculator,labdmitriy/simple_calculator,https://github.com/labdmitriy/simple_calculator,A basic calculator written in Python used to t...,True,False,False,False,...,0,32,2023-02-22T07:45:32Z,2023-02-22T07:32:57Z,2023-02-24T12:01:27Z,master,public,# SimpleCalculator\n\nA basic calculator writt...,"{""Python"": 7242, ""Makefile"": 2314}","{""Python"": 75.7848472164, ""Makefile"": 24.21515..."
69937,labdmitriy,745476462,tavily-python,labdmitriy/tavily-python,https://github.com/labdmitriy/tavily-python,A python wrapper for Tavily search API,True,False,False,False,...,0,50,2024-01-19T12:20:41Z,2024-06-03T14:04:27Z,2024-01-19T12:26:38Z,master,public,=======================\nTavily Python Wrapper...,"{""Python"": 6581}","{""Python"": 100.0}"
69938,labdmitriy,271366391,telegram_interactions,labdmitriy/telegram_interactions,https://github.com/labdmitriy/telegram_interac...,None,False,False,False,False,...,0,7,2020-06-10T19:25:53Z,2020-07-24T08:12:09Z,2020-06-24T22:46:37Z,master,public,"# Библиотека для Домашнего задания 3 (""Обработ...","{""Python"": 9663}","{""Python"": 100.0}"
69939,labdmitriy,371024975,the-hat-game,labdmitriy/the-hat-game,https://github.com/labdmitriy/the-hat-game,Learn word embedding and service deployment by...,True,False,False,False,...,0,137,2021-05-26T12:25:19Z,2021-05-26T12:25:20Z,2019-12-18T11:41:41Z,master,public,# Игра в шляпу\n\nВам предлагается поучаствова...,"{""Jupyter Notebook"": 121815, ""Python"": 3804, ""...","{""Jupyter Notebook"": 95.3810858637, ""Python"": ..."
69940,labdmitriy,591989766,writing-faster-python3,labdmitriy/writing-faster-python3,https://github.com/labdmitriy/writing-faster-p...,Code examples for the writing faster Python 3 ...,True,False,False,False,...,0,9126,2023-01-22T15:34:03Z,2023-01-22T15:37:33Z,2023-01-22T15:37:30Z,main,public,# Writing Faster Python 3\n\n## Code examples\...,"{""Python"": 27468, ""Shell"": 2636, ""Roff"": 1480}","{""Python"": 86.9680851064, ""Shell"": 8.345997973..."

In [19]:
cols_u = [
    "login", "id", "type", "html_url", "site_admin", "user_view_type",
    "name", "bio", "location", "company", "blog", "hireable",
    "followers", "following", "public_repos", "public_gists",
    "created_at", "updated_at", "twitter_username",
]
df_users_filtered = df_users[[c for c in cols_u if c in df_users.columns]]
df_users_filtered

,login,id,type,html_url,site_admin,user_view_type,name,bio,location,company,blog,hireable,followers,following,public_repos,public_gists,created_at,updated_at,twitter_username
0,Kwynto,31433211,User,https://github.com/Kwynto,False,public,Constantine Zavezeon,"Programmers have existed in all ages, and were...",Russia,None,,None,14247,7,20,2,2017-08-29T07:10:05Z,2026-03-01T17:53:12Z,None
1,K1rsN7,123446875,User,https://github.com/K1rsN7,False,public,Kirill Sukhorukov,‍💻 Data Scientist | 👨‍🎓 Student |\r\nI use @me...,"Russia, Nizhny Novgorod",Searching...,https://k1rsn7.github.io/,None,9303,9898,22,2,2023-01-24T07:44:21Z,2026-04-05T16:27:28Z,None
2,DIMFLIX,112165977,User,https://github.com/DIMFLIX,False,public,DIMFLIX,I use @meowrch btw,"Russia, Nizhny Novgorod",meowrch,https://dimflix.github.io/,None,9109,9615,19,0,2022-08-26T09:16:48Z,2026-03-17T11:34:57Z,None
3,ValdikSS,3054729,User,https://github.com/ValdikSS,False,public,ValdikSS,None,Russia,ProstoVPN.org,http://valdikss.org.ru,None,5167,0,69,24,2012-12-16T09:09:59Z,2026-03-07T22:56:11Z,None
4,nfterrax,97410466,User,https://github.com/nfterrax,False,public,NFTerraX,Crypto-Enthusiast | Web3 Community Manager | W...,Russia,NFTerraX,https://nfterrax.online,None,3484,6,4,0,2022-01-09T20:57:08Z,2026-03-09T11:51:10Z,nfterrax
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,Reavolt,41386274,User,https://github.com/Reavolt,False,public,Alexey Medvedev,Everyone underwent something that changed him,Russia,@reavolt,https://vk.com/reavolt,True,49,19,9,0,2018-07-18T16:32:47Z,2026-03-28T12:21:43Z,None
996,zapletnev,1358172,User,https://github.com/zapletnev,False,public,Igor Zapletnev,None,"Russia, Novosibirsk",None,http://www.zapletnev.me/,None,49,22,9,1,2012-01-20T13:39:25Z,2026-03-26T04:25:01Z,None
997,DoctorWebLtd,3381928,Organization,https://github.com/DoctorWebLtd,False,public,"Doctor Web, Ltd.",None,"Moscow, Russia",None,http://drweb.com,None,49,0,9,0,2013-01-25T13:57:36Z,2016-02-27T06:00:08Z,None
998,meetanthony,10683674,User,https://github.com/meetanthony,False,public,Anton Isakov,None,"Veliky Novgorod, Russia",None,http://crccalc.com/,None,49,20,17,0,2015-01-24T12:01:46Z,2026-04-05T08:44:17Z,None
999,labdmitriy,9625027,User,https://github.com/labdmitriy,False,public,Dmitry Labazkin,None,"Moscow, Russia",None,labdmitriy.github.io,True,49,64,43,0,2014-11-08T12:17:25Z,2026-03-26T18:23:36Z,None

In [20]:
df_users_filtered.to_csv("users_filtered.csv")
df_repos_filtered.to_csv("repos_filtered.csv")